### ISSUE TITLE
one-to-many eager error

### ISSUE THREAD

**Issue by kuraga** [jackdempsey/sequel_polymorphic#10]
```ruby
class Status < Sequel::Model
  one_to_many :likes, as: :likeable
end

class Like < Sequel::Model
  many_to_one :likeable, polymorphic: true
end

Like.eager(:likeable).all
```

```
vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/inflections.rb:124:in `constantize': "status" is not a valid constant name! (NameError)
	from vendor/bundle/ruby/2.2.0/gems/sequel_polymorphic-0.2.0/lib/sequel_polymorphic/sequel_polymorphic.rb:48:in `block (2 levels) in many_to_one'
	from vendor/bundle/ruby/2.2.0/gems/sequel_polymorphic-0.2.0/lib/sequel_polymorphic/sequel_polymorphic.rb:46:in `each'
	from vendor/bundle/ruby/2.2.0/gems/sequel_polymorphic-0.2.0/lib/sequel_polymorphic/sequel_polymorphic.rb:46:in `block in many_to_one'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/associations.rb:2833:in `call'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/associations.rb:2833:in `block in eager_load'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/associations.rb:2797:in `each'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/associations.rb:2797:in `eager_load'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/associations.rb:2894:in `post_load'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/dataset/actions.rb:862:in `_all'
	from vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/dataset/actions.rb:45:in `all'
	from app.rb:12:in `<main>'
```

Thanks for @Draiken and @nazipov

**Comment by kuraga** [comment]
Fix: https://github.com/jackdempsey/sequel_polymorphic/commit/661e9fb975c2fd2eb9890e29552c725dc6eb09c4

**Comment by kuraga** [comment]
Closed via https://github.com/jackdempsey/sequel_polymorphic/commit/e35f52844295c315ade7f40620697da474b6e24c

**Comment by kuraga** [comment]
A regression has been introduced. See #11. This fix has been reverted using https://github.com/jackdempsey/sequel_polymorphic/commit/9c400a10afcf6468694e5439822dd8cd9934b72b.
