### ISSUE TITLE
Sequel 5

### ISSUE THREAD

**Issue by jnylen** [jackdempsey/sequel_polymorphic#26]
Sequel 5 just got released and it removed some stuff and changed stuff that polymorphic required, such as the plugin :schema.

But also the assoc. model library got changed so it doesn't work.

```
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/dataset/query.rb:84: warning: statement not reached
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:2546: warning: assigned but unused variable - res
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:61: warning: shadowing outer local variable - model
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:67: warning: shadowing outer local variable - id_map
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:70: warning: shadowing outer local variable - model
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
Coverage report generated for Mintest to /home/jnylen/Projekt/sequel_polymorphic/coverage. 52 / 92 LOC (56.52%) covered.
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `define_method': nil is not a symbol nor a string (TypeError)
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `block in association_module_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `module_eval'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `association_module_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1911:in `association_module_private_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1952:in `def_association_instance_methods'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1822:in `associate'
	from /home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:167:in `one_to_one'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_setup.rb:75:in `<class:Question>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_setup.rb:74:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/spec_helper.rb:13:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/spec_helper.rb:13:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_polymorphic/many_to_many_association_spec.rb:1:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_polymorphic/many_to_many_association_spec.rb:1:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

**Comment by kuraga** [comment]
@jnylen solved in #27 (by you :smile: ).

What do tests show on master?

**Comment by jnylen** [comment]
Hi,
Non 5.0.0 just shows about the warning:
```ruby
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/shared/sqlite.rb:290: warning: instance variable @transaction_mode not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2510: warning: instance variable @server not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2512: warning: instance variable @this not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2541: warning: instance variable @server not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2541: warning: instance variable @server not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2541: warning: instance variable @server not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2493: warning: instance variable @singleton_setter_added not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2510: warning: instance variable @server not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/shared/sqlite.rb:290: warning: instance variable @transaction_mode not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:2510: warning: instance variable @server not initialized
```

Sequel 5 shows:
```ruby
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/dataset/query.rb:84: warning: statement not reached
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:2546: warning: assigned but unused variable - res
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:41: warning: shadowing outer local variable - model
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:47: warning: shadowing outer local variable - id_map
/home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:50: warning: shadowing outer local variable - model
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:922: warning: instance variable @overridable_methods_module not initialized
Coverage report generated for Mintest to /home/jnylen/Projekt/sequel_polymorphic/coverage. 50 / 80 LOC (62.5%) covered.
/home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `define_method': nil is not a symbol nor a string (TypeError)
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `block in association_module_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `module_eval'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1906:in `association_module_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1911:in `association_module_private_def'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1952:in `def_association_instance_methods'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1822:in `associate'
	from /home/jnylen/Projekt/sequel_polymorphic/lib/sequel/plugins/polymorphic.rb:147:in `one_to_one'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_setup.rb:74:in `<class:Question>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_setup.rb:73:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/spec_helper.rb:13:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/spec_helper.rb:13:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_polymorphic/many_to_many_association_spec.rb:1:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/spec/sequel_polymorphic/many_to_many_association_spec.rb:1:in `<top (required)>'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/jnylen/Projekt/sequel_polymorphic/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

**Comment by kuraga** [comment]
Thanks.

I'll do it after 5.1.

**Comment by jnylen** [comment]
@kuraga,
5.1 is out, have you had any looks?

**Comment by kuraga** [comment]
@jnylen yeah, sorry!

Pushed a commit. Will publish a new version for a few days.

Thanks for the report!

**Comment by kuraga** [comment]
@jnylen , bumped a new version.
